// Languages Whisper was trained on, mapped to the ISO 639-1 code
export const WHISPER_LANGUAGES: Record<string, string> = {
  English: 'en',
  Chinese: 'zh',
  German: 'de',
  Spanish: 'es',
  Russian: 'ru',
  Korean: 'ko',
  French: 'fr',
  Japanese: 'ja',
  Portuguese: 'pt',
  Turkish: 'tr',
  Polish: 'pl',
  Catalan: 'ca',
  Dutch: 'nl',
  Arabic: 'ar',
  Swedish: 'sv',
  Italian: 'it',
  Indonesian: 'id',
  Hindi: 'hi',
  Finnish: 'fi',
  Vietnamese: 'vi',
  Hebrew: 'he',
  Ukrainian: 'uk',
  Greek: 'el',
  Malay: 'ms',
  Czech: 'cs',
  Romanian: 'ro',
  Danish: 'da',
  Hungarian: 'hu',
  Tamil: 'ta',
  Norwegian: 'no',
  Thai: 'th',
  Urdu: 'ur',
  Croatian: 'hr',
  Bulgarian: 'bg',
  Lithuanian: 'lt',
  Latin: 'la',
  Maori: 'mi',
  Malayalam: 'ml',
  Welsh: 'cy',
  Slovak: 'sk',
  Telugu: 'te',
  Persian: 'fa',
  Latvian: 'lv',
  Bengali: 'bn',
  Serbian: 'sr',
  Azerbaijani: 'az',
  Slovenian: 'sl',
  Kannada: 'kn',
  Estonian: 'et',
  Macedonian: 'mk',
  Breton: 'br',
  Basque: 'eu',
  Icelandic: 'is',
  Armenian: 'hy',
  Nepali: 'ne',
  Mongolian: 'mn',
  Bosnian: 'bs',
  Kazakh: 'kk',
  Albanian: 'sq',
  Swahili: 'sw',
  Galician: 'gl',
  Marathi: 'mr',
  Punjabi: 'pa',
  Sinhala: 'si',
  Khmer: 'km',
  Shona: 'sn',
  Yoruba: 'yo',
  Somali: 'so',
  Afrikaans: 'af',
  Occitan: 'oc',
  Georgian: 'ka',
  Belarusian: 'be',
  Tajik: 'tg',
  Sindhi: 'sd',
  Gujarati: 'gu',
  Amharic: 'am',
  Yiddish: 'yi',
  Lao: 'lo',
  Uzbek: 'uz',
  Faroese: 'fo',
  'Haitian Creole': 'ht',
  Pashto: 'ps',
  Turkmen: 'tk',
  Nynorsk: 'nn',
  Maltese: 'mt',
  Sanskrit: 'sa',
  Luxembourgish: 'lb',
  Myanmar: 'my',
  Tibetan: 'bo',
  Tagalog: 'tl',
  Malagasy: 'mg',
  Assamese: 'as',
  Tatar: 'tt',
  Hawaiian: 'haw',
  Lingala: 'ln',
  Hausa: 'ha',
  Bashkir: 'ba',
  Javanese: 'jw',
  Sundanese: 'su',
  Cantonese: 'yue',
};

export interface SttLanguageOption {
  name: string;
  // Undefined is the automatic entry: the engine detects the spoken language
  // itself, at the cost of a detection pass on every transcription.
  code?: string;
}

// The offered languages, in table order. Kept as a module constant rather than
// rebuilt per render: the list is fixed and a hundred entries long.
export const STT_LANGUAGE_OPTIONS: readonly SttLanguageOption[] =
  Object.entries(WHISPER_LANGUAGES).map(([name, code]) => ({ name, code }));
