import React from 'react';
import { MarkdownDocument } from 'components';

const TERMS_MARKDOWN = `# Terms & Conditions

These Terms & Conditions ("Terms") govern your use of the **NobodyWho Chat** mobile application (the "App"), provided by **NobodyWho ApS** (CVR-nr. 46025350) ("NobodyWho", "we", "us", or "our"). By downloading, installing, or using the App, you agree to be bound by these Terms. If you do not agree, please do not use the App.

## 1. The App

NobodyWho Chat lets you download large language models and run them directly on your device to chat with them offline. Model inference and your conversation history are processed and stored locally on your device.

## 2. Eligibility

You must be at least 16 years old, or the age of digital consent in your country, to use the App. By using the App you confirm that you meet this requirement.

## 3. Licence

We grant you a limited, non-exclusive, non-transferable, and revocable licence to use the App for your personal, non-commercial purposes, subject to these Terms.

## 4. Models and Third-Party Content

The App lets you download language models provided by third parties. These models are subject to their own licences, and you are responsible for reviewing and complying with them. We do not own, control, or guarantee the accuracy, safety, or suitability of any model or its output.

## 5. AI-Generated Output

Responses generated by the models are produced automatically and may be inaccurate, incomplete, biased, or offensive. Output does not constitute professional advice. You are solely responsible for evaluating any output before relying on it.

## 6. Acceptable Use

You agree not to use the App to:

- violate any applicable law or regulation;
- infringe the rights of others;
- generate or distribute unlawful, harmful, or abusive content.

## 7. Intellectual Property

The App, including its design, code, and trademarks, is owned by NobodyWho ApS and protected by applicable laws. These Terms do not grant you any rights to our trademarks or branding.

## 8. Disclaimer of Warranties

The App is provided "as is" and "as available", without warranties of any kind, whether express or implied, including fitness for a particular purpose and non-infringement.

## 9. Limitation of Liability

To the maximum extent permitted by law, NobodyWho ApS shall not be liable for any indirect, incidental, or consequential damages arising from your use of, or inability to use, the App.

## 10. Changes to These Terms

We may update these Terms from time to time. Your continued use of the App after the changes take effect constitutes acceptance of the revised Terms.

## 11. Governing Law

These Terms are governed by the laws of Denmark, without regard to its conflict-of-law principles. Any disputes shall be subject to the exclusive jurisdiction of the Danish courts.

## 12. Contact

NobodyWho ApS
CVR-nr. 46025350
Email: contact@nobodywho.ooo

_Last updated: 11 June 2026_
`;

export const TermsScreen: React.FC = () => {
  return <MarkdownDocument markdown={TERMS_MARKDOWN} />;
};
